org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4096M
kotlin.code.style=official

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true

# Application Versioning
app.versionName=1.0.0
app.versionCode=1
