package com.notes.client.canvas.export

import com.notes.client.canvas.spline.CatmullRomConverter
import com.notes.client.canvas.spline.StrokePoint
import com.notes.common.models.CanvasLayer
import com.notes.common.models.CmnManifest
import com.notes.common.models.InkPoint
import com.notes.common.models.InkStroke
import com.notes.common.models.ToolType
import kotlin.math.max
import kotlin.math.roundToInt

/**
 * Standard W3C Scalable Vector Graphics (SVG) exporter for handwritten canvas layers.
 * Adheres to ADR Q17 and cmn-file-format skill.
 */
object SvgExporter {

    private fun formatCoord(value: Float): String {
        val totalCents = (value * 100f).roundToInt()
        val isNeg = totalCents < 0
        val absCents = kotlin.math.abs(totalCents)
        val whole = absCents / 100
        val frac = absCents % 100
        val prefix = if (isNeg) "-" else ""
        return when {
            frac == 0 -> "$prefix$whole"
            frac % 10 == 0 -> "$prefix$whole.${frac / 10}"
            frac < 10 -> "$prefix$whole.0$frac"
            else -> "$prefix$whole.$frac"
        }
    }

    /**
     * Exports a CmnManifest document into an infinite-resolution W3C SVG XML string.
     */
    fun exportToSvg(manifest: CmnManifest, defaultWidth: Float = 1200f, defaultHeight: Float = 1600f): String {
        return exportLayersToSvg(
            layers = manifest.layers,
            title = manifest.title,
            defaultWidth = defaultWidth,
            defaultHeight = defaultHeight
        )
    }

    /**
     * Converts a collection of CanvasLayers into an SVG document string.
     */
    fun exportLayersToSvg(
        layers: List<CanvasLayer>,
        title: String = "Canvas Note",
        defaultWidth: Float = 1200f,
        defaultHeight: Float = 1600f
    ): String {
        // Calculate dynamic height if strokes exceed default continuous roll height
        var maxY = defaultHeight
        for (layer in layers) {
            for (stroke in layer.strokes) {
                for (point in stroke.points) {
                    if (point.y > maxY) {
                        maxY = point.y + 100f
                    }
                }
            }
        }

        val widthStr = formatCoord(defaultWidth)
        val heightStr = formatCoord(maxY)

        val sb = StringBuilder()
        sb.appendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
        sb.appendLine("<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 $widthStr $heightStr\" width=\"$widthStr\" height=\"$heightStr\">")
        sb.appendLine("  <title>${escapeXml(title)}</title>")
        sb.appendLine("  <!-- Generated by NotesAlltogether CMN Engine -->")

        for (layer in layers) {
            if (!layer.isVisible) continue
            val layerOpacity = formatCoord(layer.opacity.coerceIn(0f, 1f))
            sb.appendLine("  <g id=\"${escapeXml(layer.id)}\" opacity=\"$layerOpacity\">")

            for (stroke in layer.strokes) {
                if (stroke.tool == ToolType.VECTOR_ERASER || stroke.points.isEmpty()) continue

                val isHighlighter = stroke.tool == ToolType.HIGHLIGHTER
                val strokeOpacity = if (isHighlighter) {
                    formatCoord(0.4f * stroke.opacity)
                } else {
                    formatCoord(stroke.opacity)
                }

                val strokeWidth = formatCoord(stroke.strokeWidth)
                val color = escapeXml(stroke.colorHex)

                if (stroke.points.size == 1) {
                    val p = stroke.points.first()
                    val radius = formatCoord(max(1f, stroke.strokeWidth / 2f))
                    sb.appendLine(
                        "    <circle cx=\"${formatCoord(p.x)}\" cy=\"${formatCoord(p.y)}\" r=\"$radius\" fill=\"$color\" opacity=\"$strokeOpacity\" />"
                    )
                } else if (stroke.points.size == 2) {
                    val p0 = stroke.points[0]
                    val p1 = stroke.points[1]
                    val d = "M ${formatCoord(p0.x)} ${formatCoord(p0.y)} L ${formatCoord(p1.x)} ${formatCoord(p1.y)}"
                    sb.appendLine(
                        "    <path d=\"$d\" stroke=\"$color\" stroke-width=\"$strokeWidth\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill=\"none\" opacity=\"$strokeOpacity\" />"
                    )
                } else {
                    val strokePoints = stroke.points.map { StrokePoint.fromInkPoint(it) }
                    val segments = CatmullRomConverter.calculateSplineSegments(strokePoints)
                    if (segments.isNotEmpty()) {
                        val pathD = StringBuilder()
                        val first = segments[0]
                        pathD.append("M ${formatCoord(first.p1.x)} ${formatCoord(first.p1.y)}")
                        for (seg in segments) {
                            pathD.append(" C ${formatCoord(seg.c1.x)} ${formatCoord(seg.c1.y)}, ${formatCoord(seg.c2.x)} ${formatCoord(seg.c2.y)}, ${formatCoord(seg.p2.x)} ${formatCoord(seg.p2.y)}")
                        }
                        sb.appendLine(
                            "    <path d=\"$pathD\" stroke=\"$color\" stroke-width=\"$strokeWidth\" stroke-linecap=\"round\" stroke-linejoin=\"round\" fill=\"none\" opacity=\"$strokeOpacity\" />"
                        )
                    }
                }
            }

            // Render shapes
            for (shape in layer.shapes) {
                val color = escapeXml(shape.colorHex)
                val sw = formatCoord(shape.strokeWidth)
                val dashAttr = if (shape.lineStyle == "DASHED") " stroke-dasharray=\"12,10\"" else ""
                val hw = kotlin.math.abs(shape.width) / 2f
                val hh = kotlin.math.abs(shape.height) / 2f
                when (shape.type) {
                    "STRAIGHT_LINE" -> {
                        sb.appendLine("    <line x1=\"${formatCoord(shape.x - hw)}\" y1=\"${formatCoord(shape.y - hh)}\" x2=\"${formatCoord(shape.x + hw)}\" y2=\"${formatCoord(shape.y + hh)}\" stroke=\"$color\" stroke-width=\"$sw\"$dashAttr stroke-linecap=\"round\" />")
                    }
                    "RECTANGLE" -> {
                        sb.appendLine("    <rect x=\"${formatCoord(shape.x - hw)}\" y=\"${formatCoord(shape.y - hh)}\" width=\"${formatCoord(shape.width)}\" height=\"${formatCoord(shape.height)}\" fill=\"none\" stroke=\"$color\" stroke-width=\"$sw\"$dashAttr />")
                    }
                    "CIRCLE" -> {
                        sb.appendLine("    <circle cx=\"${formatCoord(shape.x)}\" cy=\"${formatCoord(shape.y)}\" r=\"${formatCoord(hw)}\" fill=\"none\" stroke=\"$color\" stroke-width=\"$sw\"$dashAttr />")
                    }
                    "ELLIPSE" -> {
                        sb.appendLine("    <ellipse cx=\"${formatCoord(shape.x)}\" cy=\"${formatCoord(shape.y)}\" rx=\"${formatCoord(hw)}\" ry=\"${formatCoord(hh)}\" fill=\"none\" stroke=\"$color\" stroke-width=\"$sw\"$dashAttr />")
                    }
                    "TRIANGLE" -> {
                        val pts = "${formatCoord(shape.x)},${formatCoord(shape.y - hh)} ${formatCoord(shape.x + hw)},${formatCoord(shape.y + hh)} ${formatCoord(shape.x - hw)},${formatCoord(shape.y + hh)}"
                        sb.appendLine("    <polygon points=\"$pts\" fill=\"none\" stroke=\"$color\" stroke-width=\"$sw\"$dashAttr />")
                    }
                }
            }

            // Render text boxes
            for (tb in layer.textBoxes) {
                val color = escapeXml(tb.colorHex)
                val fs = formatCoord(tb.fontSize)
                sb.appendLine("    <text x=\"${formatCoord(tb.x)}\" y=\"${formatCoord(tb.y + tb.fontSize)}\" font-size=\"$fs\" fill=\"$color\">${escapeXml(tb.text)}</text>")
            }

            sb.appendLine("  </g>")
        }

        sb.appendLine("</svg>")
        return sb.toString()
    }

    private fun escapeXml(text: String): String {
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
    }
}
